name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Deploy to Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT}" > ${HOME}/firebase-key.json
        firebase use --add jbhs-solutions
        firebase deploy --only hosting
